languageCode = "zh-Hans"
theme = "moments"
paginate = 10
paginatePath = '.'

[markup]
    [markup.highlight]
        codeFences = true
        lineNos = true
        lineNumbersInTable = false
        style = "pastie"
        tabWidth = 4

[params]
    title = "Moments Demo"
    signature = "The only journey is the one within."
    cover = "https://cdn.pixabay.com/photo/2018/03/13/22/53/puzzle-3223941_1280.jpg"

    name = "Moments Official"
    avatar = "icon.png"

    infiniteScroll = false
    
    [params.features]
        pangu = true

    [params.experimental]
        comment = false

